name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ansible-later:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ansible-later
        uses: patrickjahns/ansible-later-action@v1
        with:
          config: ".later.yml"
          path: "**/*.yml"

  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ANSIBLE: "2.10"
          - ANSIBLE: "3.4"
          - ANSIBLE: "4.3"
          - ANSIBLE: "4.3"
            MOLECULE_DISTRO: ubuntu1804
          - ANSIBLE: "4.3"
            MOLECULE_DISTRO: ubuntu2004
          - ANSIBLE: "4.3"
            MOLECULE_DISTRO: debian10
          - ANSIBLE: "4.3"
            MOLECULE_DISTRO: debian11
          - ANSIBLE: "4.3"
            MOLECULE_DISTRO: centos7
          - ANSIBLE: "4.3"
            MOLECULE_DISTRO: centos8
          - ANSIBLE: "4.3"
            MOLECULE_DISTRO: fedora31
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip list
          pip install tox tox-gh-actions
      - name: Run molecule
        env:
          ANSIBLE: ${{ matrix.ANSIBLE }}
          MOLECULE_DISTRO: ${{ matrix.MOLECULE_DISTRO }}
        run: |
          tox -- pip list
          tox -- molecule test --all --destroy always
